/**
 * Builds the architecture docs:
 *   docs/architecture/*.mmd -> public/diagrams/*.svg
 *   docs/architecture/*.md  -> lib/architecture.generated.ts
 *
 *   pnpm diagrams
 *
 * Both run here rather than in the browser, so neither mermaid (~500KB) nor a
 * markdown parser ships to the client for content that never changes at runtime.
 */
import { chromium } from "playwright";
import { marked } from "marked";
import { readFile, readdir, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve, basename } from "node:path";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = resolve(ROOT, "docs/architecture");
const OUT = resolve(ROOT, "public/diagrams");

// Workstation palette, so diagrams sit natively in the content pane.
const THEME = {
  primaryColor: "#c8c4b8",
  primaryTextColor: "#14181a",
  primaryBorderColor: "#14181a",
  lineColor: "#5c605d",
  secondaryColor: "#e08a2e",
  tertiaryColor: "#e2ded2",
  background: "#e2ded2",
  mainBkg: "#c8c4b8",
  nodeBorder: "#14181a",
  clusterBkg: "#e2ded2",
  fontFamily: "ui-monospace, SFMono-Regular, monospace",
  fontSize: "14px",
};

const mermaidSrc = await readFile(
  resolve(ROOT, "node_modules/mermaid/dist/mermaid.min.js"),
  "utf8",
);

await mkdir(OUT, { recursive: true });
const files = (await readdir(SRC)).filter((f) => f.endsWith(".mmd"));
if (!files.length) {
  console.error(`no .mmd files in ${SRC}`);
  process.exit(1);
}

const browser = await chromium.launch();
const page = await browser.newPage();
await page.setContent("<!doctype html><body><div id='host'></div></body>");
await page.addScriptTag({ content: mermaidSrc });

/**
 * Mermaid emits width="100%" and no height. Inside an <img> a percentage width
 * cannot resolve, so the SVG has zero intrinsic size and renders as broken.
 * Give it concrete dimensions from the viewBox.
 */
function withIntrinsicSize(svg: string) {
  const vb = svg.match(/viewBox="([-\d.\s]+)"/);
  if (!vb) return svg;
  const [, , w, h] = vb[1].trim().split(/\s+/).map(Number);
  if (!w || !h) return svg;
  return svg
    .replace(/\swidth="[^"]*"/, ` width="${Math.round(w)}"`)
    .replace(/<svg\s/, `<svg height="${Math.round(h)}" `)
    .replace(/\sstyle="max-width:[^"]*"/, "");
}

let failed = 0;
for (const file of files) {
  const id = basename(file, ".mmd");
  const definition = await readFile(resolve(SRC, file), "utf8");
  try {
    const svg = await page.evaluate(
      async ({ definition, theme, id }) => {
        // @ts-expect-error injected global
        const m = mermaid;
        // htmlLabels emits <foreignObject> HTML containing unclosed <br> tags,
        // which makes the SVG invalid XML. An <img> parses SVG strictly and
        // silently fails, so labels must be real SVG text.
        m.initialize({
          startOnLoad: false,
          theme: "base",
          themeVariables: theme,
          htmlLabels: false,
          flowchart: { htmlLabels: false },
        });
        const { svg } = await m.render(`d-${id}`, definition);
        return svg;
      },
      { definition, theme: THEME, id },
    );
    const sized = withIntrinsicSize(svg);
    await writeFile(resolve(OUT, `${id}.svg`), sized, "utf8");
    console.log(`  ok  ${id}.svg  ${(sized.length / 1024).toFixed(1)}KB`);
  } catch (e) {
    failed++;
    console.log(`  FAIL ${id}: ${(e as Error).message.split("\n")[0].slice(0, 120)}`);
  }
}

await browser.close();

// Markdown bodies, pre-rendered into a bundled module so no parser ships.
const docs = (await readdir(SRC)).filter((f) => f.endsWith(".md"));
const entries: string[] = [];
for (const file of docs) {
  const id = basename(file, ".md");
  const md = await readFile(resolve(SRC, file), "utf8");
  const html = await marked.parse(md, { async: true });
  entries.push(`  ${JSON.stringify(id)}: ${JSON.stringify(html)},`);
  console.log(`  ok  ${id}  ${(html.length / 1024).toFixed(1)}KB html`);
}

await writeFile(
  resolve(ROOT, "lib/architecture.generated.ts"),
  [
    "// Generated by scripts/diagrams.mts. Do not edit by hand.",
    "// Source: docs/architecture/*.md",
    "",
    "export const architectureDocs: Record<string, string> = {",
    ...entries,
    "};",
    "",
  ].join("\n"),
  "utf8",
);

if (failed) process.exit(1);
console.log(`\n${files.length - failed} diagram(s) + ${docs.length} doc(s) built`);
